apiVersion: v1
kind: Pod
metadata:
  name: nginx-fundamentos
  labels:
    app: nginx-fundamentos
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80